models/Project.php
<?php

/**
 * This is the model class for table "{{projects}}".
 *
 * The followings are the available columns in table '{{projects}}':
 * @property integer $id
 * @property string $title
 * @property string $slug
 * @property string $description
 * @property integer $category_id 
 * @property integer $participants
 * @property integer $least_participants 
 * @property integer $max_participants
 */
class Project extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 *
	 * @param string $className active record class name.
	 *
	 * @access public
	 * @return Project the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{project}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		return array(
			array('title, user_id, category_id', 'required'),
			array('user_id, category_id, participants, least_participants, max_participants', 'numerical', 'integerOnly' => true),
			array('title, slug', 'length', 'max' => 70),

			array('id, title, slug, description, category_id, participants, least_participants, max_participants', 'safe'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		return array(
			'theUser' => array(self::BELONGS_TO, 'User', 'user_id'),
			'theCategory' => array(self::BELONGS_TO, 'ProjectCategory', 'category_id'),
			'theWiki' => array(self::HAS_ONE, 'ProjectWiki', 'project_id'),
			'dates' => array(self::HAS_MANY, 'ProjectDate', 'project_id'),
			'staff' => array(self::HAS_MANY, 'ProjectStaff', 'project_id'),
			'images' => array(self::HAS_MANY, 'ProjectImage', 'project_id'),
		);
	}
	
	public function defaultScope() {
		return array(
			'with' => array(
				'theUser',
				'theCategory',
				'theWiki',
				'staff',
				'dates',
				'images',
			)
		);
	}
	
	public function scopes() {
		$t = $this->getTableAlias();
		return array(
			'index' => array(
				'limit' => 10,
				'with' => array(
					'dates' => array(
						'condition' => 'date_end >= NOW()',
					),
				)
			),
			'dashboard' => array(
				'limit' => 5,
				'with' => array(
					'dates' => array(
						'condition' => 'date_end >= NOW()',
					),
				)
			),
		);
	}
	
	public function behaviors() {
		return array(
			'sluggable' => array(
				'class' => 'application.modules.project.extensions.behaviors.SluggableBehavior.SluggableBehavior',
				'columns' => array('title'),
				'unique' => true,
				'update' => false,
			),
		);
	}
	
	/**
	 * Get all categories
	 */
	public function getCategories() {
		$categories = ProjectCategory::model()->findAll();
		
		return EBootstrap::listData($categories, 'id', 'title');
	}
	
	/**
	 * Get the HTML encoded description
	 */
	public function getDescriptionEncode() {
		return $this->description;
	}
	
	/**
	 * Get overview of participants
	 */
	public function getParticipantsOverview() {
		$html = '';
		if ($this->max_participants > 0) {
			if ($this->max_participants > $this->participants + 2)
				$label = 'success';
			elseif ($this->max_participants > $this->participants)
				$label = 'warning';
			else
				$label = 'important';
			
			$html .= EBootstrap::ilabel(Yii::t('Project', '{current}/{max}', array(
				'{current}' => $this->participants,
				'{max}' => $this->max_participants,
			)), $label)." ";
		}
		if ($this->least_participants > 0) {
			if ($this->least_participants > $this->participants)
				$label = 'warning';
			else
				$label = 'success';
			
			$html .= EBootstrap::ilabel(Yii::t('Project', ' von mindestens {least}', array(
				'{least}' => $this->least_participants,
			)), $label)." ";
		}
		
		return trim($html);
	}
	
	/**
	 * Get overview of participants for guests
	 */
	public function getParticipantsOverviewGuest() {
		$html = '';
		
		if ($this->max_participants > 0) {
			if ($this->max_participants > $this->participants + 2)
				$html .= EBootstrap::ilabel(Yii::t('Project', 'Es sind noch Plätze frei.'), 'success');
			elseif ($this->max_participants > $this->participants)
				$html .= EBootstrap::ilabel(Yii::t('Project', 'Es sind nur noch wenige Plätze frei!'), 'warning');
			else
				$html .= EBootstrap::ilabel(Yii::t('Project', 'Es sind leider keine Plätze mehr frei!'), 'important');
		}
		else {
			$html .= EBootstrap::ilabel(Yii::t('Project', 'Es sind noch Plätze frei!'), 'success');
		}
		
		return trim($html);
	}
	
	/**
	 * Check if project has a thumbnail
	 *
	 * @return boolean
	 */
	public function hasThumbnail() {
		if (count($this->images)) {
			return true;
		}
		
		return false;
	}
	
	/**
	 * Returns the src of the thumbnail
	 */
	public function getThumbnailSrc($size = 'thumbnail') {
		if ($this->hasThumbnail()) {
			$path = Yii::app()->basePath.'/../images/projects/'.$this->id.'/';
			$url = Yii::app()->request->baseUrl.'/images/projects/'.$this->id.'/';
			
			foreach ($this->images as $image) {
				if (file_exists($path.$image->filename.'_'.$size))
					return $url.$image->filename.'_'.$size;
			}
		}
		
		return '';
	}
	
	/**
	 * Get the width of the thumbnail
	 *
	 * @param $size Thumbnail type
	 *
	 * @return integer
	 */
	public function getThumbnailWidth($size = 'thumbnail') {
		$formats = $this->images[0]->formats;
		$i = 0;
		
		while ($formats[$i]['title'] != $size) {
			$i++;
		}
		
		if (isset($formats[$i]['width']))
			return $formats[$i]['width'];
		else
			return 0;
	}
	
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('Project', 'ID'),
			'title' => Yii::t('Project', 'Titel'),
			'slug' => Yii::t('Project', 'Permalink'),
			'description' => Yii::t('Project', 'Beschreibung'),
			'category_id' => Yii::t('Project', 'Kategorie'),
			'user_id' => Yii::t('Project', 'Admin'),
			'participantsOverview' => Yii::t('Project', 'Teilnehmer'),
			'participants' => Yii::t('Project', 'Momentane Anzahl Teilnehmer'),
			'least_participants' => Yii::t('Project', 'Mindest-Teilnehmer Zahl'),
			'max_participants' => Yii::t('Project', 'Maximal-Teilnehmer Zahl'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		$t = $this->getTableAlias();

		$criteria=new CDbCriteria;

		$criteria->compare("$t.id",$this->id);
		$criteria->compare("$t.title",$this->title,true);
		$criteria->compare("$t.slug",$this->slug,true);
		$criteria->compare("$t.user_id",$this->user_id);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

models/ProjectDate.php
<?php

/**
 * This is the model class for table "{{projects_dates}}".
 *
 * The followings are the available columns in table '{{projects_dates}}':
 * @property integer $id
 * @property integer $project_id
 * @property string $date_start
 * @property string $date_end
 */
class ProjectDate extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return ProjectDate the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{project_date}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		return array(
			array('project_id, date_start, date_end', 'required'),
			array('project_id', 'numerical', 'integerOnly' => true),
			array('all_day', 'boolean'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		return array(
			'theProject' => array(self::BELONGS_TO, 'Project', 'project_id'),
		);
	}
	
	public function defaultScope() {
		$t = $this->getTableAlias(false, false);

		return array(
			'order' => "$t.date_start ASC",
		);
	}
	
	public function scopes() {
		$t = $this->getTableAlias();
		
		return array(
			'active' => array(
				'condition' => "$t.date_end < NOW()",
			),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('Project.Date', 'ID'),
			'project_id' => Yii::t('Project.Date', 'Projekt'),
			'date_start' => Yii::t('Project.Date', 'Anfang'),
			'date_end' => Yii::t('Project.Date', 'Ende'),
			'all_day' => Yii::t('Project.Date', 'Ganztägig'),
		);
	}
	
	/**
	 * Outputs date range
	 */
	public function getDateRange() {
		if (date('Y-m-d', strtotime($this->date_start)) == date('Y-m-d', strtotime($this->date_end))) {
			return $this->date_start . ' - ' . date('H:i', strtotime($this->date_end));
		}
		else {
			return $this->date_start . ' - ' . $this->date_end;
		}
	}
	
	public function beforeValidate() {
		if (!empty($this->date_start))
			$this->date_start = date('Y-m-d H:i:s', strtotime($this->date_start));
		
		if (!empty($this->date_end))
			$this->date_end = date('Y-m-d H:i:s', strtotime($this->date_end));
		
		return parent::beforeValidate();
	}
	
	public function afterFind() {
		if (!empty($this->date_start)) {
			if (date('H:i', strtotime($this->date_start)) == '00:00') {
				$this->date_start = date('d.m.Y', strtotime($this->date_start));
			}
			else {
				$this->date_start = date('d.m.Y H:i', strtotime($this->date_start));
			}
		}
		
		if (!empty($this->date_end)) {
			if (date('H:i', strtotime($this->date_end)) == '00:00') {
				$this->date_end = date('d.m.Y', strtotime($this->date_end));
			}
			else {
				$this->date_end = date('d.m.Y H:i', strtotime($this->date_end));
			}
		}
		
		return parent::afterFind();
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		$t = $this->getTableAlias();

		$criteria=new CDbCriteria;

		$criteria->compare("$t.id",$this->id);
		$criteria->compare("$t.project_id",$this->project_id);
		$criteria->compare("$t.date_start",$this->date_start,true);
		$criteria->compare("$t.date_end",$this->date_end,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

controllers/ProjectController.php
<?php

class ProjectController extends Controller
{
	/**
	 * Default layout.
	 *
	 * @access public
	 * @var string the default layout for the views.
	 */
	public $layout = '//layouts/admin';

	/**
	 * Get the controller filters.
	 *
	 * @access public
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 *
	 * @access public
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('index', 'view', 'viewTitle'),
				'users' => array('*'),
			),
			array('allow',
				'actions' => array('create', 'update', 'viewAdmin'),
				'roles' => array(User::LEVEL_STAFF),
			),
			array('allow',
				'actions'=>array('admin', 'delete'),
				'roles' => array(User::LEVEL_BOARD),
			),
			array('deny',
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular project by ID.
	 *
	 * @param integer $id the ID of the model to be displayed
	 *
	 * @access public
	 * @return void
	 */
	public function actionView($id)
	{
		$model = $this->_loadModel($id);
		if (is_null($model))
			throw new CHttpException(404);
		
		$this->layout = '//layouts/column1';
		
		$this->render(
			'view',
			array(
				'model' => $model,
			)
		);
	}
	
	/**
	 * Displays a particular project by title.
	 *
	 * @param integer $id the ID of the model to be displayed
	 *
	 * @access public
	 * @return void
	 */
	public function actionViewTitle($title)
	{
		$this->layout = '//layouts/column1';
		
		$model = Project::model()->findByAttributes(array(
			'slug' => $title,
		));
		
		if (is_null($model))
			throw new CHttpException(404);
		
		$this->actionView($model->id);
	}
	
	/**
	 * Displays a particular project by ID.
	 *
	 * @param integer $id the ID of the model to be displayed
	 *
	 * @access public
	 * @return void
	 */
	public function actionViewAdmin($id)
	{
		$model = $this->_loadModel($id, array('images'));

		$dates = new ProjectDate;
		$dates->project_id = $model->id;

		$staff = new ProjectStaff;
		$staff->project_id = $model->id;
		
		//Reorder images
		if (isset($_POST['image_id'])) {
			$order = array();
			
			foreach ($_POST['image_id'] as $key => $imageId) {
				$imageId = @intval($imageId);
				$orderId = @intval($_POST['order_id'][$key]);
				
				$order[$imageId] = $orderId;
			}
			
			foreach ($images as $image) {
				$change = false;
				if (isset($order[$image->id]) and ($order[$image->id] != $image->order_id)) {
					$change = true;
					$image->order_id = $order[$image->id];
					$image->save();
				}
				
				if ($change) {
					$project = Project::model()->findByPk($id);
					$images = $project->images;
					Yii::app()->user->setFlash('success', Yii::t('Project.Image', 'Reihenfolge der Bilder geändert.'));
				}
			}
			
			if (Yii::app()->request->isAjaxRequest) {
				Yii::app()->end();
			}
		}

		$this->render(
			'viewAdmin',
			array(
				'model' => $model,
				'dates' => $dates,
				'staff' => $staff,
				'images' => $model->images,
			)
		);
	}

	/**
	 * Creates a new project.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 *
	 * @access public
	 * @return void
	 */
	public function actionCreate()
	{
		$model = new Project;
		$model->user_id = Yii::app()->user->id;

		if (isset($_POST['Project'])) {
			$model->attributes = $_POST['Project'];
			if ($model->save())
				$this->redirect(array('view', 'id' => $model->id));
		}

		$this->render(
			'create',
			array(
				'model' => $model,
			)
		);
	}

	/**
	 * Updates a particular project.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $id the ID of the model to be updated
	 *
	 * @access public
	 * @return void
	 */
	public function actionUpdate($id)
	{
		$model = $this->_loadModel($id);

		if (isset($_POST['Project'])) {
			$model->attributes = $_POST['Project'];

			if ($model->save())
				$this->redirect(array('viewAdmin', 'id' => $model->id));
		}

		$this->render(
			'update',
			array(
				'model' => $model,
			)
		);
	}

	/**
	 * Deletes a particular project.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 *
	 * @param integer $id the ID of the model to be deleted
	 *
	 * @access public
	 * @return void
	 */
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		} else {
			throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
		}
	}

	/**
	 * Lists all projects.
	 *
	 * @access public
	 * @return void
	 */
	public function actionIndex($year = null, $month = null, $day = null)
	{
		$this->layout = '//layouts/column1';
		
		//List projects where the end of the project is in the future
		if (!is_null($year) and !is_null($month) and !is_null($day)) {
			// [int hour [, int minute [, int second [, int month [, int day [, int year
			$year = intval($year);
			$month = intval($month);
			$day = intval($day);
			
			$date = mktime(0, 0, 0, $month, $day, $year);
			
			$where = "
				p.id = d.project_id AND
				DATE(d.date_start) <= '" . date('Y-m-d', $date) . "' AND DATE(d.date_end) >= '" . date('Y-m-d', $date) . "'
			";
			
			$curDate = Yii::t('Project', 'am {date}', array('{date}' => date('d.m.Y', $date)));
		}
		elseif (!is_null($year) and !is_null($month)) {
			$year = intval($year);
			$month = intval($month);
			
			$date_start = mktime(0, 0, 0, $month, 1, $year);
			$date_end = mktime(23, 59, 59, $month+1, 0, $year);
			
			$where = "
				p.id = d.project_id AND
				DATE(d.date_start) <= '" . date('Y-m-d', $date_start) . "' AND DATE(d.date_end) >= '" . date('Y-m-d', $date_end) . "'
			";
			
			$curDate = Yii::t('Project', 'im {date}', array('{date}' => strftime('%B %G', $date_start)));
		}
		else {
			$where = "
				p.id = d.project_id AND 
				d.date_end >= NOW()
			";
			
			$curDate = '';
		}
		
		$sql = "
			SELECT DISTINCT 
				p.* 
			FROM 
				{{project}} as p, 
				{{project_date}} as d 
			WHERE 
				" . $where . "
			ORDER BY 
				d.date_end ASC;";
		
		$projects = Project::model()->index()->findAllBySql($sql);
		
		$this->render('index',array(
			'projects' => $projects,
			'curDate' => $curDate,
		));
	}

	/**
	 * Manages all projects.
	 *
	 * @access public
	 * @return void
	 */
	public function actionAdmin()
	{
		$model = new Project('search');
		
		$model->unsetAttributes();
		
		if (isset($_GET['Project']))
			$model->attributes = $_GET['Project'];

		$this->render(
			'admin',
			array(
				'model' => $model,
			)
		);
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 *
	 * @param integer the ID of the model to be loaded
	 *
	 * @access private
	 * @return Project
	 */
	private function _loadModel($id, $with = array())
	{
		$model = Project::model()->with($with)->findByPk($id);
		
		if (is_null($model))
			throw new CHttpException(404, Yii::t('Project', 'Das Projekt existiert leider nicht!'));

		return $model;
	}
}

views/project/_form.php
<?php
$form = $this->beginWidget('EBootstrapActiveForm', array(
	'id' => 'project-form',
	'horizontal' => true,
)); 
?>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->bootstrapTextField($model, 'title'); ?>

	<?php echo $form->bootstrapTextField($model, 'slug', array('class' => 'slug', 'data-title' => 'Project_title')); ?>
	
	<?php echo $form->bootstrapTextArea($model, 'description'); ?>
	
	<?php echo $form->beginControlGroup($model, 'category_id'); ?>
		<?php echo $form->labelEx($model, 'category_id'); ?>
		<?php echo $form->beginControls($model, 'category_id'); ?>
			<?php echo $form->dropDownList($model, 'category_id', $model->categories); ?>
			<?php echo $form->error($model, 'category_id'); ?>
		<?php echo $form->endControls($model, 'category_id'); ?>
	<?php echo $form->endControlGroup($model, 'category_id'); ?>
	
	<?php echo $form->bootstrapTextField($model, 'participants'); ?>
	
	<?php echo $form->bootstrapTextField($model, 'least_participants'); ?>
	
	<?php echo $form->bootstrapTextField($model, 'max_participants'); ?>

	<?php echo $form->beginActions(); ?>
		<?php echo EBootstrap::submitButton($model->isNewRecord ? Yii::t('Project', 'Erstellen') : Yii::t('Project', 'Speichern'), 'success', '', false, $model->isNewRecord ? 'plus' : 'ok', true); ?>
	<?php echo $form->endActions(); ?>

<?php $this->endWidget(); ?>

views/project/_view.php
<div class="row">
	<div class="col-sm-3 project-sidebar portlet">
		<?php if ($data->hasThumbnail()): ?>
			<p>
				<a href="<?php echo $this->createUrl('/project/project/viewTitle', array('title' => $data->slug)); ?>">
					<img src="<?php echo $data->thumbnailSrc; ?>" class="thumbnail">
				</a>
			</p>
		<?php endif; ?>
		
		<?php if (count($data->dates)): ?>
			<h3 class="portlet-title"><?php echo EBootstrap::icon('calendar'); ?> <?php echo Yii::t('Project', 'Termine'); ?></h3>
			<ul>
				<?php foreach ($data->dates as $date): ?>
					<li><?php echo $date->dateRange; ?></li>
				<?php endforeach; ?>
			</ul>
		<?php endif; ?>

		<?php if ((Yii::app()->user->isStaff()) and (count($data->staff))): ?>
			<h3 class="portlet-title"><?php echo Yii::t('Project', 'Mitarbeiter'); ?></h3>
			<ul>
				<?php foreach ($data->staff as $staff): ?>
					<li><?php echo isset($staff->theUser->id) ? EBootstrap::link($staff->theUser->name, array('/user/user/profile', 'id' => $staff->theUser->id)) : $staff->user_name; ?></li>
				<?php endforeach; ?>
			</ul>
		<?php endif; ?>
	
	</div>
	
	<div class="col-sm-9 project-content">

		<h2><?php echo EBootstrap::link($data->title, array('/project/project/viewTitle', 'title' => $data->slug)); ?></h2>
		
		<p>
			<strong><?php echo Yii::t('Project', 'Teilnehmer'); ?></strong>: 
			<?php if (!Yii::app()->user->isGuest): ?>
				<?php echo $data->participantsOverview; ?>
			<?php else: ?>
				<?php echo $data->participantsOverviewGuest; ?>
			<?php endif; ?>
		</p>
		
		<?php if (!empty($data->description)): ?>
			<p>
				<?php echo $data->descriptionEncode; ?>
			</p>
		<?php endif; ?>

	</div>
</div>

views/project/admin.php
<?php
$this->breadcrumbs=array(
	Yii::t('Project', 'Projekte'),
);
 
$this->beginWidget(
	'AdminWidget', 
	array(
		'title' => Yii::t('Project', 'Projekte verwalten'),
		'buttons' => array(
			EBootstrap::ibutton(Yii::t('Project', 'Erstellen'), array('/project/project/create'), '', 'mini', '', 'plus', false, array('title' => Yii::t('Project', 'Projekt erstellen')))
		),
		'icon' => 'th-list',
		'table' => true,
	)
);

$this->widget(
	'EBootstrapGridView', 
	array(
		'id' => 'project-grid',
		'dataProvider' => $model->search(),
		'filter' => $model,
		'columns' => array(
			'id',
			'title',
			array(
				'name' => 'participantsOverview',
				'value' => '$data->participantsOverview',
				'type' => 'html',
				'filter' => false,
			),
			array(
				'class'=>'EBootstrapButtonColumn',
				'template' => '{viewAdmin}{update}{delete}',
				'buttons' => array(
					'viewAdmin' => array(
						'label' => '<icon class="icon icon-search" title="'.Yii::t('Project', 'Projekt ansehen').'"></i>',
						'url' => 'Yii::app()->createUrl("/project/project/viewAdmin", array("id" => $data->id))',
						'imageUrl' => false,
					),
				),
			),
		),
		'summaryText' => false,
	)
); 

$this->endWidget();

views/project/create.php
<?php
$this->breadcrumbs=array(
	Yii::t('Project', 'Projekte') => array('admin'),
	Yii::t('Project', 'Erstellen'),
);

$this->beginWidget(
	'AdminWidget', 
	array(
		'title' => Yii::t('Project', 'Projekt erstellen'),
		'icon' => 'plus',
	)
);

$this->renderPartial(
	'_form', 
	array(
		'model' => $model
	)
); 

$this->endWidget();

views/project/view.php
<?php
$this->title[] = $model->title;

$this->breadcrumbs=array(
	Yii::t('Project', 'Projekte') => $this->createUrl('/project/project/index'),
	$model->title,
);
?>

<div id="project-view">
	<?php if ($model->hasThumbnail()): ?>
		<p id="project-headline">
			<img src="<?php echo $model->getThumbnailSrc('header'); ?>" width="<?php echo $model->getThumbnailWidth('header'); ?>">
		</p>
	<?php endif; ?>
	
	<div class="row">
		<div class="span3 project-sidebar portlet">

			<?php if (count($model->dates)): ?>
				<h3 class="portlet-title"><?php echo Yii::t('Project', 'Termine'); ?></h3>
				<ul class="unstyled">
					<?php foreach ($model->dates as $date): ?>
						<li><?php echo $date->dateRange; ?></li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>
			<p>
				<?php if (Yii::app()->user->isStaff()): ?>
					<?php echo EBootstrap::ibutton(Yii::t('Project.Date', 'Termin'), array('/project/projectDate/create', 'id' => $model->id), 'success', '', false, 'plus', true); ?></li>
				<?php endif; ?>
			</p>
	
			<?php if ((Yii::app()->user->isStaff()) and (count($model->staff))): ?>
				<h3 class="portlet-title"><?php echo Yii::t('Project', 'Mitarbeiter'); ?></h3>
				<ul class="unstyled">
					<?php foreach ($model->staff as $staff): ?>
						<li><?php echo isset($staff->theUser->id) ? EBootstrap::link($staff->theUser->name, array('/user/user/profile', 'id' => $staff->theUser->id)) : $staff->user_name; ?></li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>
			
			<p>
				<?php if (Yii::app()->user->isStaff()): ?>
					<?php echo EBootstrap::ibutton(Yii::t('Project.Staff', 'Mitarbeiter'), array('/project/projectStaff/create', 'id' => $model->id), 'success', '', false, 'plus', true); ?></li>
				<?php endif; ?>
			</p>

		</div>
		
		<div id="project-content" class="span6">
			<h2><?php echo $model->title; ?></h2>
			
			<p>
				<strong><?php echo Yii::t('Project', 'Teilnehmer'); ?></strong>: 
				<?php if (!Yii::app()->user->isGuest): ?>
					<?php echo $model->participantsOverview; ?>
				<?php else: ?>
					<?php echo $model->participantsOverviewGuest; ?>
				<?php endif; ?>
			</p>
			
			<?php if (!empty($model->description)): ?>
				<p>
					<?php echo $model->descriptionEncode; ?>
				</p>
			<?php endif; ?>
			
			<?php if (Yii::app()->user->isStaff()): ?>
				<p>
					<?php echo EBootstrap::ibutton(Yii::t('Project', 'Projekt bearbeiten'), array('/project/project/viewAdmin', 'id' => $model->id), 'default', '', false, 'pencil'); ?>
				</p>
			<?php endif; ?>
	
		</div>
		
		<div class="span3">
			<?php
				$this->widget('application.modules.project.portlets.Calendar', array(
					'month' => date('m'),
		        	'year' => date('Y'),
		        	'project' => $model->id
				));
				
				$this->widget('application.modules.project.portlets.Projects');
			?>
		</div>
	</div>
</div>